// flow-typed signature: f21035a11b2f88f78d2eac208fb312e4
// flow-typed version: <<STUB>>/i2c-bme280_v^1.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i2c-bme280'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i2c-bme280' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i2c-bme280/BME280' {
  declare module.exports: any;
}

declare module 'i2c-bme280/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i2c-bme280/BME280.js' {
  declare module.exports: $Exports<'i2c-bme280/BME280'>;
}
declare module 'i2c-bme280/gulpfile.js' {
  declare module.exports: $Exports<'i2c-bme280/gulpfile'>;
}
